# Generated by Django 4.0.4 on 2022-05-28 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_of_organizer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='activity_name',
            field=models.CharField(default="Activity's name", max_length=64, unique=True),
        ),
        migrations.AddField(
            model_name='categories',
            name='category_name',
            field=models.CharField(default="Category's name", max_length=64, unique=True),
        ),
        migrations.AddField(
            model_name='family',
            name='family_name',
            field=models.CharField(default='Family_name', max_length=64, unique=True),
        ),
    ]
