# Generated by Django 4.0.4 on 2022-05-29 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_of_organizer', '0002_activities_activity_name_categories_category_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinf',
            name='family',
        ),
        migrations.AddField(
            model_name='userinf',
            name='families',
            field=models.ManyToManyField(to='project_of_organizer.family'),
        ),
        migrations.AddField(
            model_name='userinf',
            name='user_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
