# Generated by Django 4.0.4 on 2022-05-31 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_of_organizer', '0003_remove_userinf_family_userinf_families_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinf',
            name='families',
        ),
    ]
