# Generated by Django 4.0.4 on 2022-06-02 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_of_organizer', '0008_plans_start_alter_plans_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plans',
            name='duration',
        ),
        migrations.AddField(
            model_name='plans',
            name='finish',
            field=models.TimeField(default='12:15'),
        ),
    ]
