# Generated by Django 4.0.4 on 2022-06-02 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_of_organizer', '0010_alter_plans_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='plans',
            name='family',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project_of_organizer.family'),
        ),
        migrations.AlterField(
            model_name='plans',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
