# Generated by Django 4.0.4 on 2022-06-04 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_of_organizer', '0011_plans_family_alter_plans_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinf',
            name='family',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project_of_organizer.family'),
        ),
        migrations.DeleteModel(
            name='UserFamily',
        ),
    ]
