# Generated by Django 4.0.4 on 2022-06-05 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_of_organizer', '0012_userinf_family_delete_userfamily'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('start', models.TimeField(default='12:00')),
                ('finish', models.TimeField(default='12:15')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_of_organizer.activities')),
                ('family', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project_of_organizer.family')),
            ],
        ),
        migrations.CreateModel(
            name='UserEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_info', models.TextField(null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_of_organizer.events')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='itemforplan',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='itemforplan',
            name='user',
        ),
        migrations.DeleteModel(
            name='InfoAboutPlan',
        ),
        migrations.DeleteModel(
            name='ItemForPlan',
        ),
    ]
