# Generated by Django 4.0.4 on 2022-06-07 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_of_organizer', '0013_events_userevent_remove_itemforplan_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plans',
            name='extra_info',
            field=models.TextField(null=True),
        ),
    ]
