# Generated by Django 4.0.4 on 2022-06-10 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_of_organizer', '0014_plans_extra_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='plans',
            name='color',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='plans',
            name='initial',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
